[build]
  command = "npm run build"
  publish = "KASA-MAIN-LAST/dist"

[settings]
  # Ajoutez vos variables d'environnement ici si n√©cessaire

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301
